apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-spreadsheet-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-spreadsheet-api
  template:
    metadata:
      labels:
        app: google-spreadsheet-api
    spec:
      serviceAccountName: google-service
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - default-pool
      containers:
      - name: google-spreadsheet-api
        image: gcr.io/skye-personal/google-spreadsheet-api:latest-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /google-spreadsheet-api/googleDoc/health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /google-spreadsheet-api/googleDoc/health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 30
        resources:
          requests:
            memory: "300Mi"
            cpu: "300m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: google-spreadsheet-api
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: google-spreadsheet-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000